# Generated by Django 5.0.7 on 2024-08-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
